/*
 */
package com.amadeus.tpe.src.sca.scrumtimer;

import java.text.SimpleDateFormat;
import java.time.Duration;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author hiran.chaudhuri
 */
public class ConfigurationPanel extends javax.swing.JPanel {
    
    private SimpleDateFormat sdf = new SimpleDateFormat("HH:mm");
    
    /** Defines the time when this component shall automaticallz start.
     * The date will always be assumed as 'today'.
     * 
     * @param date 
     */
    public void setStart(Instant date) {
        if (date == null) {
            txtStart.setText("");
        } else {
            LocalTime lt = date.atZone(ZoneId.systemDefault()).toLocalTime();
            txtStart.setText(lt.toString());
        }
    }
    
    /** Returns the time when this component shall automatically start.
     * The date will always be assumed as 'today'.
     * 
     * @param date 
     */
    public Instant getStart() {
        try {
            LocalTime time = LocalTime.parse(txtStart.getText());
            Instant result = time.atDate(LocalDate.now()).atZone(ZoneId.systemDefault()).toInstant();
            return result;
        } catch (Exception e) {
            return null;
        }
    }
    
    public void setDuration(Duration d) {
        txtDuration.setText(d.toString());
    }
    
    public Duration getDuration() {
        try {
            Duration d = Duration.parse(txtDuration.getText());
            lblError.setText(" ");
            return d;
        }
        catch(Exception e) {
            lblError.setText(e.getLocalizedMessage());
            throw e;
        }
    }
    
    public boolean getPlaySound() {
      return cbPlaySound.isSelected();
    }
    
    public void setPlaySound(boolean playSound) {
      cbPlaySound.setSelected(playSound);
    }

    @Override
    public void validate() {
        getDuration();
        super.validate(); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * Creates new form ConfigurationPanel
     */
    public ConfigurationPanel() {
        initComponents();
        txtStart.setText("");
        
        txtDuration.setInputVerifier(new InputVerifier() {
            @Override
            public boolean verify(JComponent input) {
                String text = ((JTextField) input).getText();
                try {
                    getDuration();
                    return true;
                }
                catch(Exception e) {
                    return false;
                }
            }
        });
        
        txtDuration.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                try {
                    validate();
                }
                catch(Exception ex) {
                    // do nothing
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                try {
                    validate();
                }
                catch(Exception ex) {
                    // do nothing
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                try {
                    validate();
                }
                catch(Exception ex) {
                    // do nothing
                }
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    lblDuration = new javax.swing.JLabel();
    txtDuration = new javax.swing.JTextField();
    lblHint = new javax.swing.JLabel();
    lblError = new javax.swing.JLabel();
    btTeamMeeting = new javax.swing.JButton();
    btORM = new javax.swing.JButton();
    jButton1 = new javax.swing.JButton();
    lbStart = new javax.swing.JLabel();
    txtStart = new javax.swing.JTextField();
    cbPlaySound = new javax.swing.JCheckBox();

    setLayout(new java.awt.GridBagLayout());

    lblDuration.setText("Duration");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
    gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 10);
    add(lblDuration, gridBagConstraints);

    txtDuration.setText("jTextField1");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.gridwidth = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
    gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 10);
    add(txtDuration, gridBagConstraints);

    lblHint.setText("<html>Please enter the duration as ISO8601 format, e.g. P[n]Y[n]M[n]DT[n]H[n]M[n]S (see also <a href=\"https://en.wikipedia.org/wiki/ISO_8601#Durations\">https://en.wikipedia.org/wiki/ISO_8601#Durations</a>)</html>");
    lblHint.setVerticalAlignment(javax.swing.SwingConstants.TOP);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.gridwidth = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.ipadx = 31;
    gridBagConstraints.ipady = 10;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 10);
    add(lblHint, gridBagConstraints);

    lblError.setForeground(new java.awt.Color(255, 0, 0));
    lblError.setText(" ");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.gridwidth = 4;
    gridBagConstraints.ipadx = 409;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 10);
    add(lblError, gridBagConstraints);

    btTeamMeeting.setText("10 m");
    btTeamMeeting.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btTeamMeetingActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(18, 10, 11, 0);
    add(btTeamMeeting, gridBagConstraints);

    btORM.setText("50 m");
    btORM.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btORMActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(18, 6, 11, 0);
    add(btORM, gridBagConstraints);

    jButton1.setText("20 m");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(18, 6, 11, 0);
    add(jButton1, gridBagConstraints);

    lbStart.setText("Start");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
    gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 10);
    add(lbStart, gridBagConstraints);

    txtStart.setText("jTextField1");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
    gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 10);
    add(txtStart, gridBagConstraints);

    cbPlaySound.setText("Play sound when time is up");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.gridwidth = 4;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
    add(cbPlaySound, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents

    private void btTeamMeetingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTeamMeetingActionPerformed
        txtDuration.setText("PT10M");
    }//GEN-LAST:event_btTeamMeetingActionPerformed

    private void btORMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btORMActionPerformed
        txtDuration.setText("PT50M");
    }//GEN-LAST:event_btORMActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtDuration.setText("PT20M");
    }//GEN-LAST:event_jButton1ActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btORM;
  private javax.swing.JButton btTeamMeeting;
  private javax.swing.JCheckBox cbPlaySound;
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel lbStart;
  private javax.swing.JLabel lblDuration;
  private javax.swing.JLabel lblError;
  private javax.swing.JLabel lblHint;
  private javax.swing.JTextField txtDuration;
  private javax.swing.JTextField txtStart;
  // End of variables declaration//GEN-END:variables
}
